### ISSUE TITLE
Getting more than 10 results per search?

### ISSUE THREAD

**Issue by Hitaro** [carlosparaciari/ArXivBot#5]
Is it possible to specify ,for example, '18' as the number of search result?

**Comment by carlosparaciari** [comment]
Hi Hitaro,

yes I guess that one could modify the `\search` command by adding an option to specify the number of search results.

I am thinking at something on the line of `\search keywords res:n` with `n` the number of results we want to obtain.

However, if we add a `\next` button at the end of the search (as you suggest in issue #6), then it seems to me that specifying the number of results to be shown is unnecessary.
I will consider whether adding the `\next` button is feasible (in terms of the time I would needed to implement it). If not, then we could add the possibility to specify the number of results when using the `\search` command.

**Comment by Hitaro** [comment]
Done with another approach via #6.

Thank you @carlosparaciari
