### ISSUE TITLE
[Feature Request] next page button

### ISSUE THREAD

**Issue by Hitaro** [carlosparaciari/ArXivBot#6]
Adding the command `/next` at the bottom of results would be useful to show next results.

‌ ‌ 
‌ ‌ 
‌ ‌ 
‌ ‌ 
![capture _2017-12-15-10-18-31](https://user-images.githubusercontent.com/18015032/34034108-5aa6c1d0-e192-11e7-9701-fbf16e4a4586.png)

**Comment by carlosparaciari** [comment]
This is a good Idea I think, but I am not sure how easy I can implement it.
I will have a look and let you know.

**Comment by carlosparaciari** [comment]
OK, I have followed you suggestion and I have implemented something similar to the next command you suggested, see commit 83f3eccd3aeaa56251436f8cc3b62df4485e648d.

Now, when the user searches for a keyword, the bot will send them a message with 10 results. If there are remaining results, at the end of the message there will be an inline keyboard, with the buttons "Close" and "Next". If the user want to see the following ten results, they can click the "Next" button and the bot will **edit** the original message replacing the previous results with the new ones. There is also a button to see previous results, "Prev".

The tests I did seems to show that the bot is reasonably stable with these new features, but if you or anyone else find some bugs, please report them here!

Thanks for the suggestions Hitaro.
