### ISSUE TITLE
@search_arxiv_bot is unresponsive

### ISSUE THREAD

**Issue by egarpor** [carlosparaciari/ArXivBot#9]
Just reporting that @search_arxiv_bot is unresponsive in Telegram. Also, the linked address https://storebot.me/bot/search_arxiv_bot is apparently down.

**Comment by carlosparaciari** [comment]
Hi there!

The bot is now back online, and I resubmitted it to the Telegram bot store (it was removed, probably as it was offline for quite some time). I will update the link as soon as the bot store accepts it.

If the bot is already among your contacts in Telegram, you should be able to use it straight away. Else, you can add it by clicking on https://t.me/search_arxiv_bot

You can also clone this repo and have the bot working privately on your machine/server (in case I have to set the bot offline for a long time again).

If you experience further problems with it, please let me know (the bot is hosted on Heroku for free, so it might take some time to reply when you first contact it).

Thanks!
